# Generated by Django 2.2.1 on 2019-05-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_text', '0004_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pimage',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
