# Generated by Django 2.2.1 on 2019-05-28 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_text', '0005_book_pimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='book',
            new_name='products',
        ),
    ]
