# Generated by Django 2.2.1 on 2019-05-28 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_text', '0006_auto_20190528_0516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='uid',
        ),
    ]
