# Generated by Django 2.2.1 on 2019-05-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_text', '0007_remove_products_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='uid',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
