# Generated by Django 2.2.1 on 2019-05-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_text', '0008_products_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='userrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=40)),
                ('pid', models.CharField(max_length=40)),
                ('pname', models.CharField(max_length=40)),
                ('pprice', models.CharField(max_length=40)),
                ('pimage', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='uid',
        ),
    ]
